### PR TITLE
Upgrade dependencies

### PR DESCRIPTION
**Pull request by fkoksal**

### CODE REVIEW

**Review by vst — APPROVED** [review]
`eslint` is now in production dependencies (although I do not think that it matters for node applications).

Actually:

1. What I want to know is that it compiles, builds and works after the upgrade (did we try)?
2. As long as it works after the upgrade, we can cut a new patch release.
3. Going forward, you can ask @alioguzhan to review this.

For now, requesting changes as a response. If all is well, please ask @alioguzhan to review and cut a new release.

**Comment by vst** [comment]
Sorry, approved accidentally.

**Comment by fkoksal** [comment]
@alioguzhan since we don't remember why we have to use node here, I think we can sit together and convert this to npm and try if it works. I guess it won't take more than 1 hour. 

What do you say?

**Comment by alioguzhan** [comment]
Sure. Let's do it tomorrow @fkoksal

**Comment by alioguzhan** [comment]
OK. No more yarn. That yarn obsession came from the very first commit which is based on a template, I believe. Migrated to npm, upgraded nixpkgs to 23.11. Everything look fine. @vst @fkoksal

**Pull request merged**
